watched: check if the file exists before opening it
opening a nonexistent file deletes the resume data so better to avoid that
maybe it's on a remote filesystem that just wasn't mounted

diff --git a/watched b/watched
--- a/watched
+++ b/watched
@@ -150,9 +150,17 @@ highlight_output() {
 
 watch_or_die() {
 	if [ -n "$1" ]; then
+		# looks like a path?
+		case $1 in /?*)
+			if [ ! -e "$1" ]; then
+				>&2 echo "error: the file to watch doesn't exist!"
+				>&2 echo "the full path is: $1"
+				exit 1
+			fi
+		esac
 		exec mpv -- "$1"
 	else
-		>&2 echo "watched: no files to watch!"
+		>&2 echo "watched: no matching files!"
 		exit 1
 	fi
 }
